### ISSUE TITLE
calculateInterestDue depends on updateInterest

### ISSUE THREAD

**Issue by kosecki123** [chronologic/debt-smart-contract#6]
`calculateInterestDue` uses `lastinterestCycle` to determine interest in terms of tokens. Since `lastinterestCycle` is only updated by `updateInterest()` it leads to incorrect calculations.

Proposal:
get rid of intermediate state and minting

**Comment by adibas03** [comment]
The minting feature is presently a required feature by design for the smart contract.
https://blog.chronologic.network/chronologic-debt-smart-contracts-performance-global-partnership-9ab9716648a4

This post explains the working of the contract:
https://blog.chronologic.network/chronologic-debt-smart-contracts-poc-c174de64dd26
